# Generated by Django 5.1 on 2025-11-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cafeteria', '0003_producto_proveedor_producto_id_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(default='Proveedor Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cafeteria.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cafeteria.producto'),
        ),
    ]
